// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDS.Forms.Fabrica.Infrastructure.Data;

#nullable disable

namespace RDS.Forms.Fabrica.Infrastructure.Migrations
{
    [DbContext(typeof(RdsDbContext))]
    partial class RdsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rds")
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.BusinessUnit", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BUSINESS_UNIT");

                    b.Property<int?>("CodigoAddressNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_ADDRESS_NUMBER");

                    b.Property<string>("CodigoCompanhia")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_COMPANHIA");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_BUSINESS_UNIT");

                    b.HasKey("Codigo");

                    b.ToTable("BUSINESS_UNIT", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_DEPARTAMENTO");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<string>("DescricaoProduto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_DEPARTAMENTO");

                    b.HasKey("Codigo");

                    b.ToTable("DEPARTAMENTO", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Ficha", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FICHA");

                    b.Property<string>("CodigoBusinessUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BUSINESS_UNIT");

                    b.Property<string>("CodigoContratoManifesto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_CONTRATO_MANIFESTO");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<string>("CodigoLotId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_LOTID");

                    b.Property<int?>("CodigoPassoAtual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PASSO_ATUAL");

                    b.Property<int?>("CodigoProdutoDepto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO_DEPTO");

                    b.Property<string>("CodigoSolicitacaoTransp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_SOLICITACAO_TRANSP");

                    b.Property<string>("CodigoTipoDoctoJde")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_TIPO_DOCTO_JDE");

                    b.Property<int?>("CodigoTipoOperacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_TIPO_OPERACAO");

                    b.Property<int?>("CodigoTransportadora")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_ADDRESS_NUMBER_TRA");

                    b.Property<DateOnly?>("DataFicha")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_FICHA");

                    b.Property<DateOnly?>("DataInterfaceJde")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_INTERFACE_JDE");

                    b.Property<DateOnly?>("DataSaida")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_SAIDA");

                    b.Property<string>("NomeMotorista")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_MOTORISTA");

                    b.Property<string>("PlacaVeiculo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_PLACA_VEICULO");

                    b.HasKey("Codigo");

                    b.ToTable("FICHA", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.FichaBalanca", b =>
                {
                    b.Property<int>("CodigoFicha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FICHA");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<int?>("CodigoPesagem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PESAGEM");

                    b.Property<string>("OrigemDestino")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("IC_ORIGEM_DESTINO");

                    b.Property<decimal?>("Peso1Pesagem")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PESO_1_PESAGEM");

                    b.Property<decimal?>("Peso2Pesagem")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PESO_2_PESAGEM");

                    b.ToTable("FICHA_BALANCA", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.FichaLoadDetalhe", b =>
                {
                    b.Property<int?>("CodigoAddressNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_ADDRESS_NUMBER");

                    b.Property<string>("CodigoBusinessUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BUSINESS_UNIT");

                    b.Property<int>("CodigoFicha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FICHA");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<int?>("CodigoProduto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<string>("CodigoTipoDoctoJde")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_TIPO_DOCTO_JDE");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_PRODUTO");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_UM");

                    b.ToTable("FICHA_LOAD_DETALHE", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Filial", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<string>("CodigoBuDeposito")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BU_DEPOSITO");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_FILIAL");

                    b.Property<int?>("TipoImpressaoNf")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_TIPO_IMPRESSAO_NF");

                    b.HasKey("Codigo");

                    b.ToTable("FILIAL", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.LogSistema", b =>
                {
                    b.Property<int?>("CodigoFicha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<DateTime?>("DataLog")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_LOG");

                    b.Property<string>("DescricaoErro")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<int?>("Pendente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IC_PENDENTE");

                    b.Property<int?>("TipoLog")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.ToTable("LOG_SISTEMA", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_NOTA_FISCAL");

                    b.Property<string>("SerieNotaFiscal")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_SER_NOTA_FISCAL");

                    b.Property<string>("ChaveNfe")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_CHAVE_NFE");

                    b.Property<string>("CnpjCliente")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_CNPJ_CLIENTE");

                    b.Property<string>("CodigoBusinessUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BUSINESS_UNIT");

                    b.Property<int?>("CodigoFicha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FICHA");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<DateOnly?>("DataEmissao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_EMISSAO_NF");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_CLIENTE");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_PROTOCOLO");

                    b.Property<decimal?>("ValorTransmissao")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_TRANSMISSAO");

                    b.HasKey("Numero", "SerieNotaFiscal");

                    b.ToTable("NOTA_FISCAL", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.NotaFiscalDetalhe", b =>
                {
                    b.Property<decimal?>("AliquotaIcms")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_ALIQUOTA_ICMS");

                    b.Property<decimal?>("AliquotaIpi")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_ALIQUOTA_IPI");

                    b.Property<decimal?>("BaseReducaoIcms")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_BASE_REDUCAO_ICMS");

                    b.Property<int?>("CodigoCfo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoEan")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<int?>("CodigoProduto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<int>("NumeroNotaFiscal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_NOTA_FISCAL");

                    b.Property<decimal?>("PrecoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PRECO_UNITARIO");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_PRODUTO");

                    b.Property<string>("SerieNotaFiscal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_SER_NOTA_FISCAL");

                    b.Property<string>("SufixoCfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedidaComercial")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorCofins")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_COFINS");

                    b.Property<decimal?>("ValorIcmsSt")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_ICMS_ST");

                    b.Property<decimal?>("ValorIpi")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_IPI");

                    b.Property<decimal?>("ValorPis")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PIS");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_TOTAL");

                    b.ToTable("NOTA_FISCAL_DETALHE", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Passo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PASSO");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_PASSO");

                    b.HasKey("Codigo");

                    b.ToTable("PASSO", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PEDIDO");

                    b.Property<int?>("CodigoAddressNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_ADDRESS_NUMBER");

                    b.Property<string>("CodigoBusinessUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BUSINESS_UNIT");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<string>("CodigoTipoDoctoJde")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_TIPO_DOCTO_JDE");

                    b.Property<DateOnly?>("DataPedido")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_PEDIDO");

                    b.HasKey("Codigo");

                    b.ToTable("PEDIDO", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<int?>("CodigoAddressNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoBusinessUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<int>("CodigoPedido")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PEDIDO");

                    b.Property<int?>("CodigoProduto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<string>("CodigoTipoDoctoJde")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_PRODUTO");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_UM");

                    b.ToTable("PEDIDO_ITEM", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<string>("CodigoBusinessUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_BUSINESS_UNIT");

                    b.Property<string>("CodigoClf")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoCtf")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoEan")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_EAN");

                    b.Property<string>("CodigoProdutoLongo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_PRODUTO_LONGO");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_PRODUTO");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_UM");

                    b.Property<string>("UnidadeMedidaComercial")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_UMC");

                    b.HasKey("Codigo");

                    b.ToTable("PRODUTO", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.TipoOperacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_TIPO_OPERACAO");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<string>("ExpedicaoRecepcao")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_EXPEDICAO_RECEPCAO");

                    b.Property<string>("Interfaces")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_INTERFACES");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_TIPO_OPERACAO");

                    b.HasKey("Codigo");

                    b.ToTable("TIPO_OPERACAO", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.TipoOperacaoPasso", b =>
                {
                    b.Property<int>("CodigoTipoOperacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_TIPO_OPERACAO");

                    b.Property<int>("CodigoPasso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PASSO");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoPassoFlutuante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoPassoRetorno")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sequencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NR_ORDEM");

                    b.Property<int?>("TipoPasso")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodigoTipoOperacao", "CodigoPasso");

                    b.ToTable("TIPO_OPERACAO_PASSO", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.TipoOperacaoPassoCfg", b =>
                {
                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoTipoOperacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_TIPO_OPERACAO");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCampo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTabela")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.ToTable("TIPO_OPERACAO_PASSO_CFG", "rds");
                });

            modelBuilder.Entity("RDS.Forms.Fabrica.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_PLACA_VEICULO");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FILIAL");

                    b.Property<string>("CodigoRntc")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_RNTC_VEICULO");

                    b.Property<string>("UfVeiculo")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_UF_VEICULO");

                    b.HasKey("Placa");

                    b.ToTable("VEICULO", "rds");
                });
#pragma warning restore 612, 618
        }
    }
}
