INSERT INTO PEDIDO (CD_PEDIDO, CD_FILIAL, CD_BUSINESS_UNIT, CD_ADDRESS_NUMBER, DT_PEDIDO, CD_TIPO_DOCTO_JDE)
VALUES (1, 1, 'BU001', 1001, '2026-04-28', 'SO');

INSERT INTO PEDIDO_ITEM (CD_PEDIDO, CD_FILIAL, CD_PRODUTO, QT_PRODUTO, CD_UM)
VALUES (1, 1, 1, 10.0, 'UN');
